#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Sep 26 15:16:39 CST 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 261661a4a7444a9a96403677ca79b76a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot Dmux_1x4_4bit_t_behav xil_defaultlib.Dmux_1x4_4bit_t xil_defaultlib.glbl -log elaborate.log"
xelab -wto 261661a4a7444a9a96403677ca79b76a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot Dmux_1x4_4bit_t_behav xil_defaultlib.Dmux_1x4_4bit_t xil_defaultlib.glbl -log elaborate.log

