#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Sep 26 17:35:31 CST 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Dmux_1x4_4bit_t_behav -key {Behavioral:sim_1:Functional:Dmux_1x4_4bit_t} -tclbatch Dmux_1x4_4bit_t.tcl -view /mnt/hgfs/LogicDesignLab/lab1_advanced/Dmux_1x4_4bit_t_behav.wcfg -log simulate.log"
xsim Dmux_1x4_4bit_t_behav -key {Behavioral:sim_1:Functional:Dmux_1x4_4bit_t} -tclbatch Dmux_1x4_4bit_t.tcl -view /mnt/hgfs/LogicDesignLab/lab1_advanced/Dmux_1x4_4bit_t_behav.wcfg -log simulate.log

